image: alpine/edge
secrets:
  - fa19c627-c19e-46f1-9257-30f9a6f15516
environment:
  REPO: cmder
packages:
  - build-base
  - cmake
  - clang19-extra-tools
sources:
  - https://git.sr.ht/~ekoeppen/cmder
tasks:
  - lint: |
      cd $REPO
      find include -name '*.h' -o -name '*.hpp' | xargs clang-format -n -Werror
  - mirror-to-github: |
      if [ "$GIT_REF" == "refs/heads/main" ]
      then
        cd $REPO
        set +x
        git push --mirror "https://ekoeppen:$(cat $HOME/.token)@github.com/ekoeppen/$REPO"
      fi
